# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8161aca5dbb5333260bb35b26aabba5729f405a789d4020e55a0f60acc5bfaa89a0a1c91f1db1a47c2b1766bf688434ffaf787b3ceb81414715f5f9a617ca022
  facebook_app_id: ENV['FB_APP_ID']
  facebook_app_secret: ENV["FACEBOOK_APP_SECRET"]

test:
  secret_key_base: 05f24849bf529f8769ad95403e9af7732fbc81baade91de03dc3d51e1811c78b3637c1968efe7295924c27046d71ffa06496902b4decd9dc79f7d3aae18c8bdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: ENV['FB_APP_ID']
  facebook_app_secret: ENV["FACEBOOK_APP_SECRET"]
